import { it, expect } from 'vitest';
import { createGame } from '../game/index.js';
import { groundAt, parcelGround, landParcels, surveyLand, ownsLandAt } from './land.js';
import { workAreas, surveyWorkArea } from './operations.js';
import { pileTotal } from './piles.js';
import { tickJobs } from '../machinery/index.js';
import { createGroundAccess } from '../world3d/groundAccess.js';
import { validateSavedGame } from '../game/saveValidation.js';
import { planEarthworks } from '../earthworks/index.js';
import { tickBlasting, activeBlast } from '../blasting/index.js';
import { staffState, hireApplicant, assignWorker } from '../staff/index.js';

const finish=(g,m)=>{for(let i=0;m.job&&i<10000;i++)tickJobs(g.ctx,.1);expect(m.job).toBeNull();};
const totals=g=>g.totals();
const conserve=(before,after,cargo={})=>{
  for(const id of Object.keys(before))expect((after[id]??0)+(cargo[id]??0),id).toBeCloseTo(before[id],2);
};
it('lists two distinct, finite neighbouring fields and denies unowned excavation without mutation',()=>{
  const g=createGame({seed:20}),south=parcelGround(g.ctx,'south'),before=south.serialize();
  expect(landParcels(g.ctx).reduce((t,p)=>t+p.area,152*152)).toBeGreaterThan(2*152*152);
  expect(g.actions.buyLand('south').ok).toBe(false);
  expect(g.actions.buyLand('unknown').ok).toBe(false);
  expect(g.actions.shovelDig({x:40,z:210}).ok).toBe(false);
  expect(g.actions.digGround({x:40,z:210,radius:2,bottomY:-5,maxVolume:10}).total).toBe(0);
  expect(g.actions.dumpGround({x:40,z:210,tonnes:{gravel:1}})).toBeUndefined();
  expect(planEarthworks(g.ctx,{mode:'level',ax:30,az:220,bx:40,bz:220,width:8}).ok).toBe(false);
  expect(g.actions.quoteBlast({patternId:'pocket',x:240,z:40}).reason).toMatch(/field you own/);
  expect(south.serialize()).toEqual(before);
  expect(surveyLand(g.ctx,'south').estimates.sand).toBeGreaterThan(surveyLand(g.ctx,'ridge').estimates.sand);
  expect(surveyLand(g.ctx,'ridge').coverDepth).toBeLessThan(surveyLand(g.ctx,'south').coverDepth);
  expect(surveyLand(g.ctx,'ridge').rockTonnes).toBeGreaterThan(0);
});
it('buys once, records capital spending and leaves the existing field and random stream alone',()=>{
  const g=createGame({seed:21});g.actions.shovelDig({x:30,z:30});g.state.money=10000;
  const home=g.ctx.ground.serialize(),rng=g.state.rngState;
  expect(g.actions.buyLand('south')).toEqual({ok:true});
  expect(g.state.money).toBe(6000);expect(g.actions.buyLand('south').ok).toBe(false);
  expect(g.state.land.purchases).toHaveLength(1);expect(g.state.money).toBe(6000);
  expect(g.ctx.ground.serialize()).toEqual(home);expect(g.state.rngState).toEqual(rng);
  expect(g.state.logbook.days.at(-1)).toMatchObject({invested:4000,spending:0});
  expect(ownsLandAt(g.ctx,76,160)).toBe(true);expect(ownsLandAt(g.ctx,211,28)).toBe(false);
});
it('conserves hand-dug material moved between independent plots and restores both after saving',()=>{
  const g=createGame({seed:22});g.state.money=15000;g.actions.buyLand('south');g.actions.buyLand('ridge');
  const south=parcelGround(g.ctx,'south'),ridge=parcelGround(g.ctx,'ridge');
  const a=totals(south),b=totals(ridge),home=g.ctx.ground.serialize();
  expect(g.actions.shovelDig({x:40,z:210}).ok).toBe(true);
  const cargo={...g.state.tools.shovel.load};expect(pileTotal(cargo)).toBeGreaterThan(0);
  expect(g.actions.shovelDump({into:'ground',x:240,z:40}).ok).toBe(true);
  conserve(a,totals(south),cargo);
  for(const id of Object.keys(b))expect(totals(ridge)[id]).toBeCloseTo(b[id]+(cargo[id]??0),2);
  const saved=structuredClone(g.snapshot()),r=createGame({data:g.data,state:saved});
  expect(r.ctx.ground.serialize()).toEqual(home);
  expect(totals(parcelGround(r.ctx,'south'))).toEqual(totals(south));
  expect(totals(parcelGround(r.ctx,'ridge'))).toEqual(totals(ridge));
  expect(groundAt(r.ctx,40,210)).toBe(parcelGround(r.ctx,'south'));
  expect(()=>validateSavedGame(g.data,saved)).not.toThrow();
  saved.parcelGrounds.south.format=999;expect(()=>validateSavedGame(g.data,saved)).toThrow(/terrain format/);
});
it('routes machine digs, bucket loads, carrier tipping and earthworks to the owned field',()=>{
  const g=createGame({seed:23});g.state.money=50000;g.actions.buyLand('south');
  const south=parcelGround(g.ctx,'south'),before=totals(south),home=g.ctx.ground.serialize();
  const ex=g.actions.buyMachine('excavator','rusty').machine;
  const truck=g.actions.buyMachine('truck','rusty').machine;
  expect(g.actions.scoop(ex.id,{x:50,z:220}).ok).toBe(true);finish(g,ex);
  expect(g.actions.dumpBucket(ex.id,{machineId:truck.id}).ok).toBe(true);
  expect(g.actions.tip(truck.id,{x:60,z:230}).ok).toBe(true);finish(g,truck);
  conserve(before,totals(south));
  const r=g.actions.buildWorks({mode:'level',ax:80,az:220,bx:88,bz:220,width:8});expect(r.ok,r.reason).toBe(true);
  conserve(before,totals(south));expect(g.ctx.ground.serialize()).toEqual(home);
  expect(g.actions.bucketCut(ex.id,{x:248,z:40,bottomY:-2,radius:1}).ok).toBe(false);
});
it('runs a saved contractor cut against the purchased rock reserve and leaves Home Field unchanged',()=>{
  const g=createGame({seed:26});g.state.money=20000;g.actions.buyLand('ridge');
  const ridge=parcelGround(g.ctx,'ridge'),before=totals(ridge),home=g.ctx.ground.serialize();
  const stripped=g.actions.digGround({x:250,z:40,radius:5,bottomY:-100}).tonnes;
  const request={patternId:'pocket',x:250,z:40};
  const q=g.actions.quoteBlast(request);expect(q.ok,q.reason).toBe(true);
  expect(g.actions.startBlast(request).ok).toBe(true);
  for(let i=0;i<2000&&activeBlast(g.ctx).stage==='drilling';i++)tickBlasting(g.ctx);
  const r=createGame({data:g.data,state:structuredClone(g.snapshot())});
  expect(r.actions.chargeBlast(activeBlast(r.ctx).id).ok).toBe(true);
  for(let i=0;i<2000&&activeBlast(r.ctx).stage==='charging';i++)tickBlasting(r.ctx);
  r.ctx.blastOccupants=()=>[{x:500,z:500,r:0,label:'You'}];
  expect(r.actions.fireBlast(activeBlast(r.ctx).id).ok).toBe(true);
  for(let i=0;i<100;i++)tickBlasting(r.ctx);
  expect(r.state.blasting.fired).toBe(1);
  conserve(before,totals(parcelGround(r.ctx,'ridge')),stripped);
  expect(r.ctx.ground.serialize()).toEqual(home);
  const ex=r.actions.buyMachine('excavator','rusty').machine;
  const ground=parcelGround(r.ctx,'ridge');
  const cut=r.actions.bucketCut(ex.id,{x:250,z:40,bottomY:ground.heightAt(250,40)-.25,radius:.8});
  expect(cut.ok).toBe(true);expect(ex.load.rock).toBeGreaterThan(0);
});
it('lets an assigned operator work a purchased field with conserved heaps and bucket cargo',()=>{
  const g=createGame({seed:27});g.state.money=50000;g.state.stats.totalEarned=3500;
  g.actions.buyLand('south');const ex=g.actions.buyMachine('excavator','used').machine;
  g.dev.skipDays(1);
  const worker=hireApplicant(g.ctx,staffState(g.ctx).applicants[0].id).worker;
  expect(assignWorker(g.ctx,worker.id,'dig',{machineId:ex.id,spot:{x:45,z:220,yaw:0}}).ok).toBe(true);
  const south=parcelGround(g.ctx,'south'),before=totals(south),home=g.ctx.ground.serialize();
  g.advance(1000);
  expect(worker.stats.dug).toBeGreaterThan(0);
  conserve(before,totals(south),ex.load);
  expect(g.ctx.ground.serialize()).toEqual(home);
});
it('keeps legacy work-area IDs, adds purchased surveys and switches navigation explicitly',()=>{
  const g=createGame({seed:24});expect(workAreas(g.ctx)).toHaveLength(9);g.state.money=10000;g.actions.buyLand('south');
  expect(workAreas(g.ctx)).toHaveLength(18);
  expect(workAreas(g.ctx)[0].id).toBe('0-0');
  expect(surveyWorkArea(g.ctx,'south/1-1').estimates.sand).toBeGreaterThan(0);
  g.actions.setWorkArea('south/1-1');g.actions.navigateLand('ridge');
  expect(g.state.operations.workAreaId).toBeNull();expect(g.state.player.navigationLandId).toBe('ridge');
  g.actions.navigateFleet(g.state.machines[0].id);expect(g.state.player.navigationLandId).toBeNull();
  g.actions.navigateLand('south');g.actions.setWorkArea('south/1-1');expect(g.state.player.navigationLandId).toBeNull();
});
it('shows unowned terrain without allowing traffic or excavation to change it; legacy saves start with no purchases',()=>{
  const g=createGame({seed:25}),world=createGroundAccess(g.ctx),south=parcelGround(g.ctx,'south');
  expect(world.inside(40,210)).toBe(true);expect(world.workable(40,210)).toBe(false);
  expect(world.heightAt(40,210)).toBe(south.heightAt(40,210));
  const before=south.serialize();world.applyTraffic({fromX:39,fromZ:210,x:40,z:210,width:2,weight:12000,heading:0,moisture:1,slip:1});
  expect(south.serialize()).toEqual(before);
  const old=structuredClone(g.snapshot());delete old.land;delete old.parcelGrounds;
  const restored=createGame({data:g.data,state:old});expect(landParcels(restored.ctx).every(p=>!p.owned)).toBe(true);
  expect(restored.state.money).toBe(g.state.money);
});
